"""adicionando_timestamp_dev

Revision ID: 7f2e33fe8de6
Revises: 7b6eaf6fa9f9
Create Date: 2026-06-24 00:33:06.534598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f2e33fe8de6'
down_revision: Union[str, None] = '7b6eaf6fa9f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provasfamilia', sa.Column('timestamp_dev', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provasfamilia', 'timestamp_dev')
    # ### end Alembic commands ###
