"""criando tabelas no banco

Revision ID: 9b835e1d6652
Revises: 
Create Date: 2026-06-10 11:06:01.218704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9b835e1d6652'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('familia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('cor', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('prova',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('teto', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('inscrito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('rg', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('familia_id', sa.Integer(), nullable=True),
    sa.Column('check_in', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['familia_id'], ['familia.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome'),
    sa.UniqueConstraint('rg')
    )
    op.create_table('provasfamilia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_familia', sa.Integer(), nullable=False),
    sa.Column('id_prova', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_familia'], ['familia.id'], ),
    sa.ForeignKeyConstraint(['id_prova'], ['prova.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provasfamilia_id_familia'), 'provasfamilia', ['id_familia'], unique=False)
    op.create_index(op.f('ix_provasfamilia_id_prova'), 'provasfamilia', ['id_prova'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provasfamilia_id_prova'), table_name='provasfamilia')
    op.drop_index(op.f('ix_provasfamilia_id_familia'), table_name='provasfamilia')
    op.drop_table('provasfamilia')
    op.drop_table('inscrito')
    op.drop_table('prova')
    op.drop_table('familia')
    # ### end Alembic commands ###
