"""ajuste model inscrito

Revision ID: bfdbb6a4a93e
Revises: 7f2e33fe8de6
Create Date: 2026-06-24 00:44:42.575585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfdbb6a4a93e'
down_revision: Union[str, None] = '7f2e33fe8de6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provasfamilia_id_familia'), table_name='provasfamilia')
    op.drop_index(op.f('ix_provasfamilia_id_prova'), table_name='provasfamilia')
    op.drop_table('provasfamilia')
    op.drop_constraint(op.f('inscrito_nome_key'), 'inscrito', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('inscrito_nome_key'), 'inscrito', ['nome'], postgresql_nulls_not_distinct=False)
    op.create_table('provasfamilia',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_familia', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_prova', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qtd_pontos', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp_dev', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_familia'], ['familia.id'], name=op.f('provasfamilia_id_familia_fkey')),
    sa.ForeignKeyConstraint(['id_prova'], ['prova.id'], name=op.f('provasfamilia_id_prova_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('provasfamilia_pkey'))
    )
    op.create_index(op.f('ix_provasfamilia_id_prova'), 'provasfamilia', ['id_prova'], unique=False)
    op.create_index(op.f('ix_provasfamilia_id_familia'), 'provasfamilia', ['id_familia'], unique=False)
    # ### end Alembic commands ###
