"""adicionando_pontuacao_prova_familia

Revision ID: d8966021de81
Revises: 58ecc5b03167
Create Date: 2026-06-23 23:14:17.012106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8966021de81'
down_revision: Union[str, None] = '58ecc5b03167'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provasfamilia', sa.Column('qtd_pontos', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provasfamilia', 'qtd_pontos')
    # ### end Alembic commands ###
